version: "3"
services: 
  api: 
    build:  .
    ports: 
        - 8000:8000
    volumes:
        - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    environment: 
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT = 5432
      - DATABASE_PASSWORD=3311
      - DATABASE_NAME = fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=ae5c9f57d4f7e7e47741bf070bda197102bef70e02b214351c4bc60a979162cf
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=3311
      - POSTGRES_DB=fastapi

    volumes: 
      - postgres-db:/var/lib/postgresql/data
  
volumes: 
  postgres-db: 