version: "3"
services: 
  api: 
    image: sergeychukhno/fastapi
    ports: 
        - 80:8000
   
    environment: 
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT} 
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERBANE}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHN}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCES_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATAVASE_NAME}

    volumes: 
      - postgres-db:/var/lib/postgresql/data
  
volumes: 
  postgres-db: 